"""
Django settings for ecommerce2 project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
#root of project

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'csqwlmc8s55o($rt6ozh7u+ui9zb-et00w$d90j8$^!nvj41_r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

ADMINS = (
		("Siddhant", "sid10on10@gmail.com"),

		)

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'yourgmail@gmail.com'
EMAIL_HOST_PASSWORD = 'yourpassword'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

''' 
If using gmail, you will need to
unlock Captcha to enable Django 
to  send for you:
https://accounts.google.com/displayunlockcaptcha
'''



# Application definition

INSTALLED_APPS = (
    #django app
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #third party apps
    'crispy_forms',
    'registration',
    #my apps
    'newsletter',
	'pybb',
	)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
	'pybb.middleware.PybbMiddleware',

)

ROOT_URLCONF = 'ecommerce2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_in_env", "static_root")
    
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static_in_pro", "our_static"),
    #os.path.join(BASE_DIR, "static_in_env"),
    #'/var/www/static/',
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_in_env", "media_root")

PYBB_AUTO_USER_PERMISSIONS = True
PYBB_PERMISSION_HANDLER = 'pybb.permissions.DefaultPermissionHandler'
PYBB_ANONYMOUS_VIEWS_CACHE_BUFFER = 1
#PYBB_PREMODERATION =
PYBB_NICE_URL = True
PYBB_DEFAULT_TITLE = "Chem Portal"
PYBB_TEMPLATE = 'base.html'
PYBB_DEFAULT_TIME_ZONE = 5.5
PYBB_ATTACHMENT_ENABLE = True
PYBB_ATTACHMENT_SIZE_LIMIT = 20971520
PYBB_ATTACHMENT_UPLOAD_TO = 'protected/forum/attachment'

#PYBB_FREEZE_FIRST_POST = True
PYBB_FORUM_PAGE_SIZE = 25
PYBB_TOPIC_PAGE_SIZE = 15

#PYBB_DEFAULT_AUTOSUBSCRIBE = False
PYBB_DISABLE_SUBSCRIPTIONS = False
PYBB_DISABLE_NOTIFICATIONS = True
PYBB_USE_DJANGO_MAILER = True

#PYBB_MARKUP = 'bbcode'
#PYBB_MARKUP = 'markdown'
#PYBB_SMILES_PREFIX = 'pybb/emoticons'
#PYBB_SMILES = {'&gt;_&lt;': 'angry.png',':.(': 'cry.png','o_O': 'eyes.png','[]_[]': 'geek.png','8)': 'glasses.png',':D': 'lol.png',':(': 'sad.png',':O': 'shok.png','-_-': 'shy.png',':)': 'smile.png',':P': 'tongue.png',';)': 'wink.png'}

PYBB_AVATAR_HEIGHT = 80
PYBB_MAX_AVATAR_SIZE = 20000
#PYBB_DEFAULT_AVATAR_URL = settings.STATIC_URL + 'pybb/img/default_avatar.jpg'


#Crispy FORM TAGs SETTINGS
CRISPY_TEMPLATE_PACK = 'bootstrap3'


#DJANGO REGISTRATION REDUX SETTINGS
ACCOUNT_ACTIVATION_DAYS = 7
REGISTRATION_AUTO_LOGIN = True
SITE_ID = 1
LOGIN_REDIRECT_URL = '/'



